### PR TITLE
Create testing.txt

### PR DESCRIPTION
**Pull request by prietyc123**

### CODE REVIEW

**Review by savitaashture — APPROVED** [review]

**Comment by prietyc123** [comment]
@Mergifyio refresh

**Comment by avinal** [comment]
Nice 👏🏼

**Comment by avinal** [comment]
BTW it seems it is assigning to you even though you have put Savita.

**Comment by prietyc123** [comment]
> BTW it seems it is assigning to you even though you have put Savita.

I am not able to find savita while assigning 😄

**Pull request merged**
